In [1]:
import numpy as np

In [2]:
X = np.array([
              [0,0],
              [0,1],
              [1,0],
              [1,1]
              ], dtype="float32")

In [3]:
y = np.array([
              [0],
              [1],
              [1],
              [0]
            ], dtype="float32")

In [4]:
w = np.array([
              [1],
              [2]
            ], dtype="float32")

In [5]:
b = np.array([3], dtype="float32")

In [8]:
def sigmoid(h):
    return 1 / (1 * np.exp(-h))

In [9]:
hypothesis = sigmoid(np.dot(X, w) + b)

In [12]:
X.T

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [13]:
x1 = X.T[0].reshape(1,-1)

In [14]:
x1

array([[0., 0., 1., 1.]], dtype=float32)

In [15]:
w1_gred = np.sum(1/4 * np.dot(x1, (hypothesis - y)))

In [16]:
x2 = X.T[1].reshape(1,-1)

In [17]:
w2_gred = np.sum(1/4 * np.dot(x2, (hypothesis - y)))

In [18]:
b_gred = 1/4 * np.sum(hypothesis - y)

In [19]:
learning_rate = 0.1
for i in range(1000):
    print("i = ", i)
    print("*" * 100)
    for j in range(2):
        print("j = ", j)
        hypothesis = sigmoid(np.dot(X,w)+b)
        print("hypothesis = ", hypothesis)

        cost = -1/4 * np.sum(y * np.log(hypothesis) + (1 - y)* np.log(1- hypothesis))
        print("cost = ", cost)
        X_col_2d = X.T[j].reshape(1, -1)
        print("x{} = {}".format(j+1, X_col_2d))
        w_gred = 1/4 * np.sum(np.dot ( X_col_2d , (hypothesis - y)))
        print("w{}_gred = {}".format(j+1, w_gred))
        b_gred = 1/4 * np.sum(hypothesis - y)
        print("b_gred = ", b_gred)

        w[j] = w[j] - learning_rate * w_gred
        print("w{} = {}".format(j+1, w[j]))
        b = b - learning_rate * b_gred
        print("b = ", b)
        print("="*100)

i =  0
****************************************************************************************************
j =  0
hypothesis =  [[ 20.085537]
 [148.41316 ]
 [ 54.59815 ]
 [403.42877 ]]
cost =  nan
x1 = [[0. 0. 1. 1.]]
w1_gred = 114.25672912597656
b_gred =  156.13140869140625
w1 = [-10.425673]
b =  [-12.613141]
j =  1
hypothesis =  [[3.3279932e-06]
 [2.4590730e-05]
 [9.8712004e-11]
 [7.2938855e-10]]
cost =  8.412989616394043
x2 = [[0. 1. 0. 1.]]
w2_gred = -0.24999384582042694
b_gred =  -0.4999930262565613
w2 = [2.0249994]
b =  [-12.563142]
i =  1
****************************************************************************************************
j =  0
hypothesis =  [[3.4986206e-06]
 [2.6505928e-05]
 [1.0377299e-10]
 [7.8619700e-10]]
cost =  8.38174057006836
x1 = [[0. 0. 1. 1.]]
w1_gred = -0.25
b_gred =  -0.4999924898147583
w1 = [-10.400673]
b =  [-12.513143]
j =  1
hypothesis =  [[3.6779957e-06]
 [2.7864891e-05]
 [1.1185536e-10]
 [8.4742663e-10]]
cost =  8.35049057006836
x2 = [[0. 1. 

c:\programdata\anaconda3\envs\python_env\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in log
  # Remove the CWD from sys.path while we load stuff.


hypothesis =  [[6.6815912e-05]
 [1.0449764e-03]
 [4.1955004e-09]
 [6.5616149e-08]]
cost =  6.538269996643066
x2 = [[0. 1. 0. 1.]]
w2_gred = -0.24973873794078827
b_gred =  -0.49972203373908997
w2 = [2.7747824]
b =  [-9.563597]
i =  31
****************************************************************************************************
j =  0
hypothesis =  [[7.0239708e-05]
 [1.1263032e-03]
 [4.4104871e-09]
 [7.0722756e-08]]
cost =  6.5070414543151855
x1 = [[0. 0. 1. 1.]]
w1_gred = -0.2499999850988388
b_gred =  -0.4997008442878723
w1 = [-9.650684]
b =  [-9.513627]
j =  1
hypothesis =  [[7.383874e-05]
 [1.184014e-03]
 [4.753853e-09]
 [7.622852e-08]]
cost =  6.475807189941406
x2 = [[0. 1. 0. 1.]]
w2_gred = -0.24970398843288422
b_gred =  -0.49968549609184265
w2 = [2.7997527]
b =  [-9.463658]
i =  32
****************************************************************************************************
j =  0
hypothesis =  [[7.7622099e-05]
 [1.2761526e-03]
 [4.9974318e-09]
 [8.2160561e-08]]
cost 

In [20]:
w

array([[-0.0012576 ],
       [-0.00044283]], dtype=float32)

In [21]:
b

array([-0.6922062], dtype=float32)

In [22]:
np.dot(X, w) + b

array([[-0.6922062],
       [-0.692649 ],
       [-0.6934638],
       [-0.6939066]], dtype=float32)

In [23]:
sigmoid ( np.dot(X, w) + b )

array([[0.5004707 ],
       [0.50024915],
       [0.49984175],
       [0.49962044]], dtype=float32)

In [24]:
predict = sigmoid ( np.dot(X, w) + b )

In [25]:
np.where(predict > 0.5 , 1 , 0)

array([[1],
       [1],
       [0],
       [0]])