In [1]:
import numpy as np

In [2]:
X = np.array([
              [0,0],
              [0,1],
              [1,0],
              [1,1]
              ], dtype="float32")

In [3]:
y = np.array([
              [0],
              [1],
              [1],
              [0]
            ], dtype="float32")

In [4]:
w = np.array([
              [1],
              [2]
            ], dtype="float32")

In [5]:
b = np.array([3], dtype="float32")

In [6]:
def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [7]:
hypothesis = sigmoid(np.dot(X, w) + b)

In [8]:
X.T

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [9]:
x1 = X.T[0].reshape(1,-1)

In [10]:
x1

array([[0., 0., 1., 1.]], dtype=float32)

In [11]:
w1_gred = np.sum(1/4 * np.dot(x1, (hypothesis - y)))

In [12]:
x2 = X.T[1].reshape(1,-1)

In [13]:
w2_gred = np.sum(1/4 * np.dot(x2, (hypothesis - y)))

In [14]:
b_gred = 1/4 * np.sum(hypothesis - y)

In [15]:
learning_rate = 0.1
for i in range(1000):
    print("i = ", i)
    print("*" * 100)
    for j in range(2):
        print("j = ", j)
        hypothesis = sigmoid(np.dot(X,w)+b)
        print("hypothesis = ", hypothesis)

        cost = -1/4 * np.sum(y * np.log(hypothesis) + (1 - y)* np.log(1- hypothesis))
        print("cost = ", cost)
        X_col_2d = X.T[j].reshape(1, -1)
        print("x{} = {}".format(j+1, X_col_2d))
        w_gred = 1/4 * np.sum(np.dot ( X_col_2d , (hypothesis - y)))
        print("w{}_gred = {}".format(j+1, w_gred))
        b_gred = 1/4 * np.sum(hypothesis - y)
        print("b_gred = ", b_gred)

        w[j] = w[j] - learning_rate * w_gred
        print("w{} = {}".format(j+1, w[j]))
        b = b - learning_rate * b_gred
        print("b = ", b)
        print("="*100)

i =  0
****************************************************************************************************
j =  0
hypothesis =  [[0.95257413]
 [0.9933072 ]
 [0.98201376]
 [0.9975274 ]]
cost =  2.268986463546753
x1 = [[0. 0. 1. 1.]]
w1_gred = 0.24488529562950134
b_gred =  0.48135560750961304
w1 = [0.9755115]
b =  [2.9518645]
j =  1
hypothesis =  [[0.9503516 ]
 [0.99297947]
 [0.9806851 ]
 [0.9973416 ]]
cost =  2.239839792251587
x2 = [[0. 1. 0. 1.]]
w2_gred = 0.24758026003837585
b_gred =  0.4803394377231598
w2 = [1.975242]
b =  [2.9038305]
i =  1
****************************************************************************************************
j =  0
hypothesis =  [[0.9480354]
 [0.9924534]
 [0.9797539]
 [0.9971414]]
cost =  2.210663080215454
x1 = [[0. 0. 1. 1.]]
w1_gred = 0.24422383308410645
b_gred =  0.47934603691101074
w1 = [0.9510891]
b =  [2.855896]
j =  1
hypothesis =  [[0.9456226 ]
 [0.99208564]
 [0.9782678 ]
 [0.9969277 ]]
cost =  2.1817617416381836
x2 = [[0. 1. 0. 1.]]
w2_gred 

In [16]:
w

array([[0.00348961],
       [0.00570618]], dtype=float32)

In [17]:
b

array([-0.00509938], dtype=float32)

In [18]:
np.dot(X, w) + b

array([[-0.00509938],
       [ 0.00060681],
       [-0.00160976],
       [ 0.00409642]], dtype=float32)

In [19]:
sigmoid(np.dot(X, w) + b )

array([[0.49872515],
       [0.5001517 ],
       [0.49959752],
       [0.5010241 ]], dtype=float32)

In [20]:
hypothesis0 = sigmoid(np.dot(X, w) + b )

In [21]:
np.where(hypothesis0 > 0.5 , 1 , 0)

array([[0],
       [1],
       [0],
       [1]])

In [22]:
import numpy as np
import tensorflow as tf

In [23]:
X = np.array([
              [0,0],
              [0,1],
              [1,0],
              [1,1]
              ], dtype="float32")

In [24]:
y = np.array([
              [0],
              [1],
              [1],
              [0]
            ], dtype="float32")

In [25]:
w0 = tf.Variable([[1,2],[3,4]], dtype="float32")

In [26]:
b0 = tf.Variable([[0,0]], dtype="float32")

In [27]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)

In [28]:
hypothesis0

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.5       , 0.5       ],
       [0.95257413, 0.98201376],
       [0.7310586 , 0.8807971 ],
       [0.98201376, 0.99752736]], dtype=float32)>

In [29]:
w1 = tf.Variable([[5],[6]], dtype="float32")

In [30]:
b1 = tf.Variable([[0]], dtype="float32")

In [31]:
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)

In [32]:
optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=0.1)

In [33]:
for step in range(5000):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
        hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
        
        cost = -tf.reduce_mean(y * tf.math.log(hypothesis1) + (1 - y) * tf.math.log(1-hypothesis1))
        grads = tape.gradient(cost, [w0, w1, b0, b1])
        
        optimizer.apply_gradients(grads_and_vars = zip(grads, [w0, w1, b0, b1]))
        
        if step % 100 == 0:
            print(f"cost : {cost}, w0 : {w0}, w1 : {w1}")
        

cost : 4.0991926193237305, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.9000014, 1.9000086],
       [2.9000015, 3.9000084]], dtype=float32)>, w1 : <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[4.9],
       [5.9]], dtype=float32)>
cost : 0.557486355304718, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.056538 , -4.4126105],
       [ 1.2810547,  3.0600321]], dtype=float32)>, w1 : <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.6855314],
       [3.8502128]], dtype=float32)>
cost : 0.5103297829627991, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.5863266, -6.274629 ],
       [ 1.5904137,  4.880547 ]], dtype=float32)>, w1 : <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.3543904],
       [4.4116955]], dtype=float32)>
cost : 0.49529528617858887, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.8877606, -7.

In [34]:
w0

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -9.124632, -12.648875],
       [  9.688233,  12.943761]], dtype=float32)>

In [35]:
b0

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[ 4.2849154, -7.1995845]], dtype=float32)>

In [36]:
w1

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-17.03966],
       [ 17.55062]], dtype=float32)>

In [37]:
b1

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[8.180037]], dtype=float32)>

In [38]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)

In [39]:
hypothesis0

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[9.8641235e-01, 7.4630976e-04],
       [9.9999917e-01, 9.9680877e-01],
       [7.8472197e-03, 2.3984115e-09],
       [9.9222100e-01, 1.0020435e-03]], dtype=float32)>

In [40]:
predict = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)

In [41]:
predict

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[1.8131733e-04],
       [9.9982220e-01],
       [9.9967980e-01],
       [1.6498566e-04]], dtype=float32)>

In [42]:
tf.cast(predict > 0.5, dtype=tf.float32)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)>

In [43]:
predict01 = tf.cast(predict > 0.5, dtype = tf.float32)

In [44]:
ac1 = tf.equal(predict01, y)

In [45]:
ac1

<tf.Tensor: shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True]])>

In [46]:
ac2 = tf.cast(ac1, dtype = tf.float32)

In [47]:
ac2

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [48]:
ac3 = tf.reduce_mean(ac2)

In [49]:
ac3

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [50]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y), dtype = tf.float32))

In [51]:
accuracy.numpy()

1.0

In [52]:
arr = np.array([[0,1]], dtype = 'float32')

In [53]:
hypothesis0 = tf.sigmoid(tf.matmul(arr, w0) + b0)

In [54]:
predict = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)

In [55]:
predict

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.9998222]], dtype=float32)>

In [56]:
predict = tf.cast(predict > 0.5, dtype = tf.float32)

In [57]:
predict.numpy()

array([[1.]], dtype=float32)

# 심층 신경망을 이용한 XOR (tensorflow 2.x)

In [58]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np

In [59]:
X = np.array([
              [0,0],
              [0,1],
              [1,0],
              [1,1]
              ], dtype="float32")

y = np.array([0,1,1,0], dtype = 'float32')

In [60]:
model = Sequential([
    Dense(2, input_dim = 2, activation = "sigmoid"),
    Dense(1, activation = "sigmoid")
])


In [61]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [64]:
model.compile(loss = 'binary_crossentropy', optimizer = Adam(learning_rate = 0.1), metrics=['acc'])

In [65]:
model.fit(X, y, epochs = 500, verbose=0)

In [91]:
pred = model.predict(X)

In [92]:
pred

array([[0.00208232],
       [0.99734   ],
       [0.9973731 ],
       [0.00601429]], dtype=float32)

In [84]:
predict01 = tf.cast(pred > 0.5, dtype=tf.float32)

In [85]:
predict01 = tf.reshape(predict01, (1,-1))

In [102]:
tf.reduce_mean(tf.cast(predict01 == y, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>